# Site settings
title: Readers Beware...wolves!
email: samuel.j.casavant@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Like the readers are werewolves, not beware of wolves. But do that too. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sam.casavant.org/"  # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown

