# Site settings
title: Mystapost
email: 
description: > # this means to ignore newlines until "baseurl:"
  This blogs name changes every post. That's the joke.
baseurl: "http://sam.casavant.org/" # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown

