# Site settings
title: Receding Airline
email: samuel.j.casavant@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It would be nice if I could just come up with good titles. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sam.casavant.org/"  # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown

