# Site settings
title: Smasavant
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is where the Smasavant resides. 
baseurl: "" # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
