# Site settings
title: What is going on in here?
email: 
description: > # this means to ignore newlines until "baseurl:"
  Seriously, what's happening? What does any of it mean? 
baseurl: "" # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown

